# fly.toml app configuration file generated for fast2 on 2023-08-14T12:53:02+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fast2"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
